name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Prettier
        run: yarn run prettier:check

      - name: Run Embedme
        run: yarn run embedme:check

      - name: Publish to Dev.to
        uses: muncus/devto-publish-action@release/v1
        with:
          directory: "$GITHUB_WORKSPACE/content/"
          api-key: "${{ secrets.DEVTO_TOKEN }}"
          state-file: "$GITHUB_WORKSPACE/ids.json"
          
      - name: Create PR to update state file
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[CI] Update state file with published article ids"
          reviewers: ${{ github.actor }}
          token: "${{ GITHUB_CREDENTIALS }}"
          base: master
          branch: "ci/state-file-update

